package org.de.challenge.domain;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.time.LocalDate;

/**
 * Created with app.quicktype.io
 */
@lombok.Data
public class Season implements Serializable {
    @lombok.Getter(onMethod_ = {@JsonProperty("AC")})
    @lombok.Setter(onMethod_ = {@JsonProperty("AC")})
    private int ac;
    @lombok.Getter(onMethod_ = {@JsonProperty("AF")})
    @lombok.Setter(onMethod_ = {@JsonProperty("AF")})
    private int af;
    @lombok.Getter(onMethod_ = {@JsonProperty("AR")})
    @lombok.Setter(onMethod_ = {@JsonProperty("AR")})
    private int ar;
    @lombok.Getter(onMethod_ = {@JsonProperty("AS")})
    @lombok.Setter(onMethod_ = {@JsonProperty("AS")})
    private int as;
    @lombok.Getter(onMethod_ = {@JsonProperty("AST")})
    @lombok.Setter(onMethod_ = {@JsonProperty("AST")})
    private int ast;
    @lombok.Getter(onMethod_ = {@JsonProperty("AY")})
    @lombok.Setter(onMethod_ = {@JsonProperty("AY")})
    private int ay;
    @lombok.Getter(onMethod_ = {@JsonProperty("AwayTeam")})
    @lombok.Setter(onMethod_ = {@JsonProperty("AwayTeam")})
    private String awayTeam;
    @lombok.Getter(onMethod_ = {@JsonProperty("B365A")})
    @lombok.Setter(onMethod_ = {@JsonProperty("B365A")})
    private double b365A;
    @lombok.Getter(onMethod_ = {@JsonProperty("B365D")})
    @lombok.Setter(onMethod_ = {@JsonProperty("B365D")})
    private double b365D;
    @lombok.Getter(onMethod_ = {@JsonProperty("B365H")})
    @lombok.Setter(onMethod_ = {@JsonProperty("B365H")})
    private double b365H;
    @lombok.Getter(onMethod_ = {@JsonProperty("BSA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BSA")})
    private double bsa;
    @lombok.Getter(onMethod_ = {@JsonProperty("BSD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BSD")})
    private double bsd;
    @lombok.Getter(onMethod_ = {@JsonProperty("BSH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BSH")})
    private double bsh;
    @lombok.Getter(onMethod_ = {@JsonProperty("BWA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BWA")})
    private double bwa;
    @lombok.Getter(onMethod_ = {@JsonProperty("BWD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BWD")})
    private double bwd;
    @lombok.Getter(onMethod_ = {@JsonProperty("BWH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BWH")})
    private double bwh;
    @lombok.Getter(onMethod_ = {@JsonProperty("Bb1X2")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Bb1X2")})
    private int bb1X2;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAH")})
    private int bbAH;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAHh")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAHh")})
    private double bbAHh;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAv<2.5")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAv<2.5")})
    private double bbAV25;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAv>2.5")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAv>2.5")})
    private double welcomeBbAV25;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAvA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAvA")})
    private double bbAVA;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAvAHA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAvAHA")})
    private double bbAVAHA;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAvAHH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAvAHH")})
    private double bbAVAHH;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAvD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAvD")})
    private double bbAVD;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbAvH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbAvH")})
    private double bbAVH;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbMx<2.5")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbMx<2.5")})
    private double bbMX25;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbMx>2.5")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbMx>2.5")})
    private double welcomeBbMX25;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbMxA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbMxA")})
    private double bbMXA;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbMxAHA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbMxAHA")})
    private double bbMXAHA;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbMxAHH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbMxAHH")})
    private double bbMXAHH;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbMxD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbMxD")})
    private double bbMXD;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbMxH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbMxH")})
    private double bbMXH;
    @lombok.Getter(onMethod_ = {@JsonProperty("BbOU")})
    @lombok.Setter(onMethod_ = {@JsonProperty("BbOU")})
    private int bbOU;
    @lombok.Getter(onMethod_ = {@JsonProperty("Date")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Date")})
    private LocalDate date;
    @lombok.Getter(onMethod_ = {@JsonProperty("Div")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Div")})
    private String div;
    @lombok.Getter(onMethod_ = {@JsonProperty("FTAG")})
    @lombok.Setter(onMethod_ = {@JsonProperty("FTAG")})
    private int ftag;
    @lombok.Getter(onMethod_ = {@JsonProperty("FTHG")})
    @lombok.Setter(onMethod_ = {@JsonProperty("FTHG")})
    private int fthg;
    @lombok.Getter(onMethod_ = {@JsonProperty("FTR")})
    @lombok.Setter(onMethod_ = {@JsonProperty("FTR")})
    private String ftr;
    @lombok.Getter(onMethod_ = {@JsonProperty("GBA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("GBA")})
    private double gba;
    @lombok.Getter(onMethod_ = {@JsonProperty("GBD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("GBD")})
    private double gbd;
    @lombok.Getter(onMethod_ = {@JsonProperty("GBH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("GBH")})
    private double gbh;
    @lombok.Getter(onMethod_ = {@JsonProperty("HC")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HC")})
    private int hc;
    @lombok.Getter(onMethod_ = {@JsonProperty("HF")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HF")})
    private int hf;
    @lombok.Getter(onMethod_ = {@JsonProperty("HR")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HR")})
    private int hr;
    @lombok.Getter(onMethod_ = {@JsonProperty("HS")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HS")})
    private int hs;
    @lombok.Getter(onMethod_ = {@JsonProperty("HST")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HST")})
    private int hst;
    @lombok.Getter(onMethod_ = {@JsonProperty("HTAG")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HTAG")})
    private int htag;
    @lombok.Getter(onMethod_ = {@JsonProperty("HTHG")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HTHG")})
    private int hthg;
    @lombok.Getter(onMethod_ = {@JsonProperty("HTR")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HTR")})
    private String htr;
    @lombok.Getter(onMethod_ = {@JsonProperty("HY")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HY")})
    private int hy;
    @lombok.Getter(onMethod_ = {@JsonProperty("HomeTeam")})
    @lombok.Setter(onMethod_ = {@JsonProperty("HomeTeam")})
    private String homeTeam;
    @lombok.Getter(onMethod_ = {@JsonProperty("IWA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("IWA")})
    private double iwa;
    @lombok.Getter(onMethod_ = {@JsonProperty("IWD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("IWD")})
    private double iwd;
    @lombok.Getter(onMethod_ = {@JsonProperty("IWH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("IWH")})
    private double iwh;
    @lombok.Getter(onMethod_ = {@JsonProperty("LBA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("LBA")})
    private double lba;
    @lombok.Getter(onMethod_ = {@JsonProperty("LBD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("LBD")})
    private double lbd;
    @lombok.Getter(onMethod_ = {@JsonProperty("LBH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("LBH")})
    private double lbh;
    @lombok.Getter(onMethod_ = {@JsonProperty("Referee")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Referee")})
    private String referee;
    @lombok.Getter(onMethod_ = {@JsonProperty("SBA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("SBA")})
    private double sba;
    @lombok.Getter(onMethod_ = {@JsonProperty("SBD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("SBD")})
    private double sbd;
    @lombok.Getter(onMethod_ = {@JsonProperty("SBH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("SBH")})
    private double sbh;
    @lombok.Getter(onMethod_ = {@JsonProperty("SJA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("SJA")})
    private double sja;
    @lombok.Getter(onMethod_ = {@JsonProperty("SJD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("SJD")})
    private double sjd;
    @lombok.Getter(onMethod_ = {@JsonProperty("SJH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("SJH")})
    private double sjh;
    @lombok.Getter(onMethod_ = {@JsonProperty("VCA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("VCA")})
    private double vca;
    @lombok.Getter(onMethod_ = {@JsonProperty("VCD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("VCD")})
    private double vcd;
    @lombok.Getter(onMethod_ = {@JsonProperty("VCH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("VCH")})
    private double vch;
    @lombok.Getter(onMethod_ = {@JsonProperty("WHA")})
    @lombok.Setter(onMethod_ = {@JsonProperty("WHA")})
    private double wha;
    @lombok.Getter(onMethod_ = {@JsonProperty("WHD")})
    @lombok.Setter(onMethod_ = {@JsonProperty("WHD")})
    private double whd;
    @lombok.Getter(onMethod_ = {@JsonProperty("WHH")})
    @lombok.Setter(onMethod_ = {@JsonProperty("WHH")})
    private double whh;
}
